# -*- coding: utf-8 -*-
"""Copy of EEP 105 Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5CFEmIkMn4EleoCwmvKwguHEDa-u1kk
"""

#Import packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from scipy import stats
!pip install lets_plot
from lets_plot import *
LetsPlot.setup_html()

"""# Motivation

**1) Why did you pick this country?**
	Chloe: I picked this country because my dad is from South Korea and I find its story of modernization really interesting. Korea has endured many centuries of hardship and developed a 빨리빨리 (pali pali) culture, a fast paced lifestyle that sees constant evolution and adaptations to new trends or innovations. Their 빨리빨리 way of life has led to a lot of innovation that has also had a large environmental impact. However, I know that Korean people really value sustainability and there are many sustainability initiatives in Korea to try and combat their climate impact. I think that South Korea being one of the top 10 countries in the data set for the yearly CO2 emissions from the Bloomberg case study was interesting. South Korea has a slightly smaller land mass than California, being the smallest country by far in the top 10 and the 8th largest population in the group. I think this data is fascinating because the country is so small with an extremely dense population and I wanted to look into the country further.

**2) What are some facts about CO2 emissions for that country?**
	South Korea’s CO₂ emissions have risen dramatically over the past 50 years, climbing from around 62 million metric tons in 1970. Then it peaked at about 671 million metric tons in 2018 before declining to roughly 574 million in 2023 (The Global Economy, 2025a). This shift is accompanied by the country’s rapid industrialization and economic growth, as well as changes in its energy sources. Coal accounted for over 80% of emissions in the 1960s, but by 2016 its share had dropped to about 50% (Index Mundi, 2025). In 2022, South Korea was responsible for about 1.65% of global fossil CO₂ emissions and ranked among the world’s top ten emitters (Worldometer, 2025), with per capita emissions of 11.09 metric tons, more than double the global average of 4.76 (The Global Economy, 2025b). South Korea has also been a pioneer in climate policy, launching the first nationwide emissions trading system in East Asia in the early 2010s (Wikipedia, 2025a). The COVID-19 pandemic triggered a 6.4% drop in emissions in 2020 due to reduced electricity generation, lower coal use, and decreased transportation demand (Wikipedia, 2025b). While emissions have fallen from their peak, South Korea still maintains one of the highest per capita carbon footprints despite their small land mass and smaller population size.
Sources:
“Climate Change in South Korea.” Wikipedia, 8 Aug. 2025. Wikipedia, https://en.wikipedia.org/w/index.php?title=Climate_change_in_South_Korea&oldid=1304907243
“Emissions Trading Scheme in South Korea.” Wikipedia, 5 May 2025. Wikipedia, https://en.wikipedia.org/w/index.php?title=Emissions_Trading_Scheme_in_South_Korea&oldid=1288863909.
“South Korea Carbon Dioxide (CO2) Emissions per Capita - Data, Chart.” TheGlobalEconomy.Com, https://www.theglobaleconomy.com/South-Korea/Carbon_dioxide_emissions_per_capita/. Accessed 10 Aug. 2025.
“South Korea CO2 Emissions.” Worldometer, https://www.worldometers.info/co2-emissions/south-korea-co2-emissions/. Accessed 10 Aug. 2025.

“South Korea Economic Indicators.” TheGlobalEconomy.Com, https://www.theglobaleconomy.com/south-korea/. Accessed 10 Aug. 2025.

# Main Research Questions
1. How have global CO2 emission rates changed over time? In particular for South Korea (SK), and how does SK compare to other countries?

South Korea’s CO₂ emissions are substantial and shocking for a country of its size. On a per capita basis, South Koreans emit about 11.09 metric tons of CO₂ annually, more than double the global average of 4.76 metric tons (The Global Economy, 2025b). Despite some improvements in carbon intensity, with CO₂ emissions per dollar of GDP decreasing from 0.47 kg to 0.22 kg, South Korea still remains slightly above the global average (The Global Economy, 2025c). The country’s heavy reliance on coal power contributes significantly to its emissions, with coal-related emissions per capita among the highest in the G20, at over three tons per person (Ember Climate, 2024). Globally, South Korea ranks among the top ten CO₂ emitters, alongside countries like Germany and Japan (Reuters, 2024). While recent years have seen a modest decline in emissions, the country remains a major player in the global carbon footprint.


2. Are CO2 emissions in SK, global temperatures, and natural disaster rates in the US associated?

There is strong evidence linking South Korea’s rising CO₂ emissions with increased temperatures and the severity of natural disasters. For example, in March 2025, the country experienced its largest wildfire on record, which scientists attribute to climate change doubling the likelihood of such events and increasing their intensity by about 15% (Reuters, 2025a). Record-high temperatures, roughly 2°C above historical averages, combined with dry conditions, contributed to the wildfire’s severity (The Guardian, 2025). Additionally, South Korea’s recent floods, including the heavy monsoon rains of 2023—the most intense in 115 years—have been linked to climate change, which is causing more extreme and concentrated rainfall events (Wikipedia, 2025a). Average temperatures have also steadily increased, with 2023 and 2024 setting new records, reaching nearly 2°C above long-term averages (Wikipedia, 2025b). These patterns illustrate how human-driven CO₂ emissions are contributing to a warmer climate, which in turn fuels more frequent and severe natural disasters in South Korea.

References:

Ember Climate. (2024). Australia and South Korea remain the top two per capita coal power polluters. https://ember-climate.org/press-releases/australia-and-south-korea-remain-the-top-two-per-capita-coal-power-polluters

Reuters. (2024). Top 10 country emitters discharged record amount CO2. https://www.reuters.com/markets/commodities/top-10-country-emitters-discharged-record-amount-co2-2023-2024-06-21

Reuters. (2025a). South Korea’s deadly fires made twice likely by climate change, researchers say. https://www.reuters.com/sustainability/cop/south-koreas-deadly-fires-made-twice-likely-by-climate-change-researchers-say-2025-04-30

The Guardian. (2025). South Korea fires death toll rises: worst in history. https://www.theguardian.com/world/2025/mar/27/south-korea-fires-death-toll-rises-worst-in-history

The Global Economy. (2025a). Carbon dioxide emissions – South Korea. https://www.theglobaleconomy.com/south-korea/Carbon_dioxide_emissions

The Global Economy. (2025b). Carbon dioxide emissions per capita – South Korea. https://www.theglobaleconomy.com/South-Korea/Carbon_dioxide_emissions_per_capita

The Global Economy. (2025c). Carbon intensity – South Korea. https://www.theglobaleconomy.com/South-Korea/carbon_intensity

Wikipedia. (2025a). 2023 South Korea floods. https://en.wikipedia.org/wiki/2023_South_Korea_floods

Wikipedia. (2025b). Geography of South Korea. https://en.wikipedia.org/wiki/Geography_of_South_Korea

# What are the data?

**This case study uses five datasets showing:**
1. Yearly CO2 emissions by country (1751-2014):
    
    https://raw.githubusercontent.com/opencasestudies/ocs-bp-co2-emissions/master/data/raw/yearly_co2_emissions_1000_tonnes.xlsx
2. GDP per capita in terms of yearly percentage growth per capita by country (1801-2019):
    
    https://raw.githubusercontent.com/opencasestudies/ocs-bp-co2-emissions/master/data/raw/gdp_per_capita_yearly_growth.xlsx

3. Energy use per person in terms of kg of oil equivalents per capita by country (1990-2023):
   
    https://raw.githubusercontent.com/opencasestudies/ocs-bp-co2-emissions/master/data/raw/energy_use_per_person.xlsx
4. South Korea Disaster Data:
    
    https://raw.githubusercontent.com/opencasestudies/ocs-bp-co2-emissions/master/data/raw/disasters.csv

5. South Korea Temperature Data (1901-2022):
    
    https://raw.githubusercontent.com/opencasestudies/ocs-bp-co2-emissions/master/data/raw/temperature.csv

# What does it measure?

**1. Yearly CO2 emissions by country (1751-2014):**
The year-over-year percentage change in gross domestic product per person for each country. Units: percent (%) change from the previous year.

**2. GDP per capita in terms of yearly percentage growth per capita by country (1801-2019):**
The year-over-year percentage change in gross domestic product per person for each country. Units: percent (%) change from the previous year.

**3. Energy use per person in terms of kg of oil equivalents per capita by country (1990-2023):**
The average annual energy consumption per person, expressed in kilograms of oil equivalent (kgOE). This is a standardized unit to compare different energy sources.

**4. South Korea disaster data**
Number and type of natural disasters in South Korea by year (e.g., floods, typhoons, droughts). Variables may include year, type of disaster, number of events, damage cost, and casualties.

**5. South Korea Temperature Data (1901-2022):**
Average yearly temperature in South Korea over time. Units: degrees Celsius (°C).

# What does a given value for the variables ofinterest mean?
**1. Yearly CO2 emissions by country (1751-2014):**
If South Korea’s value in 2010 is 573,000, that means it emitted 573 million tonnes of CO₂ that year. Higher values indicate greater emissions, often linked to industrial activity and energy use.

**2. GDP per capita in terms of yearly percentage growth per capita by country (1801-2019):**
 A value of 3.5 for 2005 means GDP per person grew 3.5% compared to 2004. Negative values mean an economic contraction per person (e.g., during recessions).

**3. Energy use per person in terms of kg of oil equivalents per capita by country (1990-2023):**
A value of 4,500 in 2015 means that, on average, each person used energy equivalent to 4,500 kg of oil that year. Higher values generally reflect higher industrialization or consumption

**4. South Korea Disaster Data:**
If in 2007 the flood count is 3, it means three flood events were recorded in South Korea that year. Damage cost variables (if present) indicate the economic loss in specified currency units

**5. South Korea Temperature Data (1901-2022):**
A temperature of 13.2°C in 2010 means the average temperature across all months of 2010 was 13.2°C. Rising averages over decades can indicate warming trends.

# Data Import
Below, we'll read in the data with the appropriate function (depending upon whether they're in Excel or CSV format), assign them a dataframe name, and print out a few of the rows to see what the dataframes look like.
"""

#Read in the data


df_co2 = pd.read_csv("https://raw.githubusercontent.com/AmandaYun5/EEP-105-Final-Project-Data/refs/heads/main/yearly_co2_emissions_1000_tonnes.csv")
df_gdp = pd.read_csv("https://raw.githubusercontent.com/AmandaYun5/EEP-105-Final-Project-Data/refs/heads/main/gdp_per_capita_yearly_growth.csv")
df_en = pd.read_csv("https://raw.githubusercontent.com/AmandaYun5/EEP-105-Final-Project-Data/refs/heads/main/energy_use_per_person.csv")
df_nd = pd.read_csv("https://raw.githubusercontent.com/AmandaYun5/EEP-105-Final-Project-Data/refs/heads/main/sk_natural_disaster_data.csv")
df_temp = pd.read_csv("https://raw.githubusercontent.com/AmandaYun5/EEP-105-Final-Project-Data/refs/heads/main/sk_temp_data.csv")

#Yearly CO2 emissions by country (1751-2014):
df_co2.head()

#GDP per capita in terms of yearly percentage growth per capita by country (1801-2019):
df_gdp.head()

#Energy use per person in terms of kg of oil equivalents per capita by country (1990-2023):
df_en.head()

#SK data on natural disasters (1977-2025):
df_nd.head()

#SK data on temperature (1895-2019):
df_temp.head()

"""# Data Wrangling"""

# there are 192 rows of different countries and their CO2 emissoins values from 1751-2014
#some countries have missing data
#code below shows the years in our data
print(df_co2.columns)
column_names_list = list(df_co2.columns)
print(column_names_list)

#use .melt() to change data from wide to long, this makes the data a little more tidy
# changes the year columns into a single column called year with its corresponding values
# grabbing a random sample from the CO2 emissions data

CO2_emissions_long = pd.melt(
    df_co2,
    id_vars=['country'],
    var_name='Year',
    value_name='Emissions'
)

random_sample = CO2_emissions_long.sample(n=6, random_state = 123)
print (random_sample)
CO2_emissions_long

# clean and tidy the CO2 data further
df_co2_c = (
    CO2_emissions_long
    .rename(columns={'country': 'Country'})
    .assign(Year=lambda df: pd.to_numeric(df['Year']),
            Label="CO2 Emissions (Metric Tons)")
    .dropna(subset=['Emissions']) # Add this line to drop rows where 'Emissions' is NaN
)

print(df_co2_c.head())

#Yearly Growth in GDP Per Capita (GDP_PC) Data Wrangling
# checking number of rows in the GDP_pc data frame
num_rows = len(df_gdp)
print(f'Number of rows: {num_rows}')
# shows 194 rows as opposed to 50688

#checking number of columns:
num_cols = len(df_gdp.columns)
print(f'Number of columns: {num_cols}')

# there's 220 country columns and a set of columns corresponding to different years
# use .melt() to change data from wide to long, this makes the data a little more tidy changes the year columns into a single column called year with its corresponding values
df_gdp_long = pd.melt(
    df_gdp,
    id_vars=['country'],
    var_name='Year',
    value_name='GDP per capita'
)

# grabbing a random sample from the GDP per capita data

random_sample = df_gdp_long.sample(n=6, random_state = 123)
print (random_sample)

# clean and tidy the GDP_pc data further
df_gdp_c = (
    df_gdp_long
    .rename(columns={'country': 'Country'})
    .assign(Year=lambda df: pd.to_numeric(df['Year']),
            Label="GDP per Capita Yearly Growth")
     .dropna(subset=['GDP per capita']) # Add this line to drop rows where 'GDP' is NaN
)

print(df_gdp_c.head())

# cleaning the Data for Energy Use per person (E_use_pp)

# use .melt() to change data from wide to long, this makes the data a little more tidy

# changes the year columns into a single column called year with its corresponding values

df_en_long = pd.melt(
    df_en,
    id_vars=['country'],
    var_name='Year',
    value_name='Energy Use PP'
)

# grabbing a random sample from the Energy use per person data

random_sample = df_en_long.sample(n=6, random_state = 123)
print (random_sample)

# clean the E_use_pp data further:
# Convert Year to an integer
# Add a new 'Label' column
# Rename the energy use column
df_en_c = (
    df_en_long
    .rename(columns={'country': 'Country'})
    .assign(
        Year=lambda df: df['Year'].astype(int),
        Label="Energy Use (kg, oil-eq./capita)"
    )
    .rename(columns={'energy_use': 'Energy'})
        .dropna(subset=['Energy Use PP']) # Add this line to drop rows where 'Energy' is NaN
)
df_en_c

# setting seed for reproducibility, ensures that the random sample is the same every time you run the code.

np.random.seed(123)
#  grabbing 3 random rows from the Data frame
energy_use_sample = df_en_c.sample(n=3).reset_index(drop=True)
# showing the sample
print(energy_use_sample)

# checking unique values in Country column, showing different countries, picked first 10 for shorter demonstration

unique_countries = df_en_c['Country'].unique()
print("\nUnique countries in the dataset (first 10):")
print(unique_countries[:10])

# showing number of unique countries
unique_countries = df_en_c['Country'].unique()
print(f"\nTotal number of unique countries: {len(unique_countries)}")

#Now we're going to look at the SK specific data
# These data sets only gave us info for the SK

# Disasters Data Wrangling
# showing the data
df_nd

#Select only "Year" and "Disasters" columns
df_nd = df_nd.loc[:,["Start Year", "Disaster Type"]]

#Count number of disasters per year and alter the "Value" column
df_nd = df_nd.groupby("Start Year").agg("Disaster Type").count().reset_index()

#Add "Country", "Indicator", "Label" columns to show that data are from the U.S. disasters dataset
df_nd["Country"] = "South Korea"
df_nd["Indicator"] = "Disasters"
df_nd["Label"] = "Number of Disasters"

#Rename "Disaster" column to "Number of Disasters"
df_nd = df_nd.rename(columns = {"Start Year": "Year", "Disaster Type":"Value"})
df_nd_c = df_nd[["Country", "Year", "Indicator", "Value", "Label"]]
df_nd_c

#Pivot temperature data to long form
df_no_identifiers = df_temp.drop(columns=['code', 'name'])
df_temp_long = df_no_identifiers.melt(var_name='year', value_name='temperature')

#Add columns "Country," "Indicator," "Label"
df_temp_long["Country"] = "South Korea"
df_temp_long["Indicator"] = "Temperature"
df_temp_long["Label"] = "Temperature (Celsius)"

#Rename columns, select first four digits of year values (and change to numeric)
df_temp_long = df_temp_long.rename(columns = {"year":"Year", "temperature":"Value"})
df_temp_long["Year"] = df_temp_long["Year"].str[:4].astype("int64")
df_temp_c = df_temp_long[["Country", "Year", "Indicator", "Value", "Label"]]
df_temp_c

# Joining the data
df_co2_c.describe()
df_gdp_c.describe()
df_en_c.describe()
df_nd_c.describe()
df_temp_c.describe()


#Why do we need this right here? - oh just bc like i wanted to see it lol

# now we combine data sets
# merge CO2 Emissions and GDP growth per capita

data_wide = pd.merge(
    left= df_co2_c,
    right= df_gdp_c,
    on=['Country', 'Year', 'Label'],
    how='outer'
)

# then merge with Energy use per person
data_wide = pd.merge(
    left=data_wide,
    right= df_en_c,
    on=['Country', 'Year', 'Label'],
    how='outer'
)

data_wide

t = data_wide.query("Country == 'Germany'")
t.query("Year == 1862")

#  set random seed for reproducibility
np.random.seed(123)
print(data_wide.sample(n=3))

# reorder the columns for aesthetic preferences
new_column_order = [
    'Country',
    'Year',
    'Emissions',
    'GDP per capita',
    'Energy Use PP',
    'Label'
]
data_wide = data_wide[new_column_order]
np.random.seed(123)
print(data_wide.sample(n=3))

#this seems repetitive since I think the columns were already in this order
data_wide

j = data_wide.query("Country == 'Germany'")
j.query("Year ==1862")

# make long version of the data and create new variable called Indicator to indicate where the data set came from
data_long = data_wide.melt(
    id_vars=['Country', 'Year'],
    var_name='Indicator',
    value_vars=['Emissions', 'GDP per capita', 'Energy Use PP'],
    value_name = "Value"
)
data_long

#add label column afterward (including label with id_vars was making th elabels and indicator columns misalign for some values)
label_map = {
    'Emissions': 'CO2 Emissions (Metric Tons)',
    'GDP per capita': 'GDP per Capita Yearly Growth',
    'Energy Use PP': 'Energy Use (kg, oil-eq./capita)'
}
data_long['Label'] = data_long['Indicator'].map(label_map)
data_long

i = data_long.query("Country == 'Germany'")
i.query("Year ==1862")

# combine this with the US Data about Disasters and Temperature
# concat automatically handles columns that don't match by filling them with NaN just in case
# convering 'Country' column to a categorical data type in pandas
data_long = pd.concat([data_long, df_nd_c, df_temp_c])
data_long['Country'] = data_long['Country'].astype('category')
data_long = data_long.dropna()
print(data_long)
data_long

h = data_long.query("Country == 'Germany'")
h.query("Year ==1862")

# show first and last 6 rows of the combined data set
print(data_long.head(6))
print(data_long.tail(6))

# drop rows that have at least 1 NaN value
data_long_with_miss = data_long.sort_values(by='Country').reset_index(drop=True)
Final_df = data_long.dropna(subset=['Value']).sort_values(by='Country').reset_index(drop=True)
print(Final_df)
Final_df

g = Final_df.query("Country == 'Germany'")
g.query("Year ==1862")

# create a new variable called region that will indicate if Data ifro m the SK or a different country based on the Country variable
# ex: if country variable is US then new variable's value will the SK, but if the Country variable isn't equal to SK then it will be "Rest of the World"
data_long['Region'] = np.where(
    data_long['Country'] == 'South Korea',
    'South Korea',
    'Rest of the World'
)
Final_df = data_long.sort_values(by='Country')

print(Final_df)
Final_df

d = Final_df.query("Country == 'Germany'")
d.query("Year ==1862")

"""# Data Visualization"""

#Filter table to include only CO2 emissions data in order to plot emissions over time
#Sum emissions data across countries to get total emissons per year
df_co2_plot_agg = Final_df.query(
    "Indicator == 'Emissions'").groupby("Year", as_index = False)[["Value"]].sum()
df_co2_plot_agg

#Plot total CO2 emissions over time with ggplot

co2_plot = (ggplot(data = df_co2_plot_agg,
                  mapping = aes(x="Year", y="Value")
                 ) +
            geom_line(size = 1.5) +
            scale_x_continuous(format = "d", breaks = np.arange(1700, 2100, 100)) +
            labs(title = "World CO2 Emissions per Year (1751-2014)",
                y="Emissions (Metric Tonnes)",
                caption = "Limited to reporting Countries")+
            ggsize(600, 400)
               )
co2_plot

#Plot CO2 emissions by country
df_co2_plot_country = Final_df.query("Indicator == 'Emissions'")

co2_plot_by_country = (ggplot(data = df_co2_plot_country,
                  mapping = aes(x="Year", y="Value", group= "Country")
                 ) +
                geom_line(alpha = 0.4) +
                scale_x_continuous(format = "d", breaks = np.arange(1700, 2100, 100)) +
                labs(title = "Country CO2 Emissions per Year (1751-2014)",
                y="Emissions (Metric Tonnes)",
                caption = "Limited to Reporting Countries")
                      )
co2_plot_by_country

#Add another layer to highlight the SK line in blue
df_co2_plot_us = df_co2_plot_country.query("Country =='South Korea'")
co2_plot_by_country = co2_plot_by_country + geom_line(
                           data=df_co2_plot_us, mapping = aes(x="Year", y="Value", color = "Country")) + scale_color_manual(values = ["blue"])
co2_plot_by_country

n = df_co2_plot_country.query("Country == 'Germany'")
n.query("Year == 1862")

#Modify dataframe to just include top 10 emitting countries

#Create an ordered list of the top 10 emitting countries' names, top10
top10 = list(df_co2_plot_country.query("Year == 2014").sort_values(["Value"], ascending=False).iloc[:10,0])

#Create a new dataframe, df_top10, with only the top 10 emitting countries
is_in_df = df_co2_plot_country["Country"].isin(top10)
df_top10 = df_co2_plot_country[is_in_df].copy()

#Convert the values in the "Value" and "Year" columns into numeric format
df_top10["Value"] = pd.to_numeric(df_top10["Value"], errors = 'coerce')
df_top10["Year"] = pd.to_numeric(df_top10["Year"], errors = 'coerce')
df_top10

#idk why there are two values for some of the countries

#Plot top 10 emitting countries with different line colors

last_pts = df_top10.query("Year == 2014")
top10_plot = (ggplot(data = df_top10, mapping =aes(x="Year", y="Value", color = "Country")) +
                    geom_line(show_legend = False) +
              scale_color_viridis(option="viridis")+
              scale_x_continuous(format = "d", expand = (0.30, 0))+
              scale_y_continuous(expand = (0.1, 0))+
                    labs(title = "Top 10 Emissions-producing Countries in 2014 (1900-2014)",
                         x="Year",
                y="Emissions (Metric Tons)",
                subtitle = "Limited to Reporting Countries") +
              geom_text_repel(
                  data=last_pts,
                  mapping = aes(x = "Year", y="Value", label="Country"),
                  show_legend = False,
                  check_overlap = True,
                  hjust = 0,
                  vjust = 0.5,
                  nudge_x = 10,
                  nudge_y = 100000,
                  force = 95,
                  nudge_unit = 'size'
              )
                   )
top10_plot

#Turn the ascending countries list into a category list to sort the dataframe
#This is great for columns that have a certain number (10 in this case) of unique values
#but lots of repeated values.
df_top10_asc = df_top10.copy()
df_top10_asc["Country"] = pd.Categorical(
    df_top10_asc['Country'], # Use df_top10_asc here
    categories=top10,
    ordered=True)
df_top10_asc_sort = df_top10_asc.sort_values(by="Country")

#Create a "Log Value" column to use for the plot
df_top10_asc_sort["Log Value"] = np.log(df_top10_asc_sort['Value'])
df_top10_asc_sort = df_top10_asc_sort.query("Year >= 1900")
df_top10_asc_sort = df_top10_asc_sort.query("Indicator == 'Emissions'")

#Tile plot of top 10 emitting countries (lets_plot)
tile_plot = (ggplot(data = df_top10_asc_sort, mapping = aes(x="Year", y = "Country")) +
             geom_tile(aes(fill = "Log Value")) +
             scale_x_continuous(format = "d", limits = [1900, 2014])+
             scale_fill_viridis() +
             labs(title="Top 10 CO2 Emissions-producing Countries (1900-2014)",
                  subtitle = "Ordered by Emissions Produced in 2014")
            )
tile_plot

# 4) The last facet figure, 3x2 figure that shows all of the world and then just the chosen country.


#Filter the data to include 3 out of the 5 indicators
df_3_2 = Final_df[Final_df["Indicator"].isin(["Emissions", "Energy Use PP", "GDP per capita"])]
df_3_2= df_3_2.copy()

#Make values in "Value" column numeric
df_3_2["Value"] = pd.to_numeric(df_3_2["Value"], errors = "coerce")
df_3_2

#Facet figure (3x2)

three_by_two_plot = (ggplot(data=df_3_2, mapping = aes(x="Year", y="Value", group = "Country")) +
                     geom_line(size = 0.3, color = "black")+
                     facet_grid(x="Region", y="Indicator", scales = "free_y")+
                     scale_x_continuous(format = "d") +
                     labs(title= "Distribution of Indicators by Year and Value", y = "Indicator Value", color = "black")+
                     theme(
                         strip_background = element_rect(fill= "black"),
                         strip_text = element_text(color = "white", size=16, face ="bold"))
                    )

three_by_two_plot

#Filter df_final to just include US data for emissions and temperature

#Filter by indicator
df_sk_co2_temp = Final_df[Final_df["Indicator"].isin(["Emissions", "Temperature"])]

#Filter by country
df_sk_co2_temp = df_sk_co2_temp[df_sk_co2_temp["Country"].isin(["South Korea"])]

#Filter by time range
df_sk_co2_temp = df_sk_co2_temp.query("2014 >= Year >= 1980")
df_sk_co2_temp

#Facet plot with trend lines
facet_co2_temp_plot = (ggplot(data=df_sk_co2_temp, mapping = aes(x="Year", y="Value"))+
                       geom_point() +
                       scale_x_continuous(format = "d")+
                       facet_wrap(facets = "Label", scales = "free_y")+
                       geom_smooth(deg = 2, method = "loess", se=False, color = "blue", size = 0.8) +
                       theme(
                         strip_background = element_rect(color = "black", fill = "white"),
                         strip_text = element_text(color = "black", size=16))+
                       labs(title = "US Emissions and Temperatures (1980-2014)")+
                       ggsize(600, 400)
                      )
facet_co2_temp_plot

"""# Data Analysis"""

#Convert dataframe back to narrow version
df_sk_co2_temp_wide = df_sk_co2_temp.pivot(columns = "Indicator", values = "Value", index = "Year")
df_sk_co2_temp_wide.head()

#Define a function for converting to standard units
def std_units(array):
    return (array - np.mean(array))/np.std(array)

#Standardize
df_sk_co2_temp_wide_std = df_sk_co2_temp_wide.apply(std_units)
df_sk_co2_temp_wide_std["Emissions"] = pd.to_numeric(df_sk_co2_temp_wide_std["Emissions"].copy(), errors = "coerce")
df_sk_co2_temp_wide_std["Temperature"] = pd.to_numeric(df_sk_co2_temp_wide_std["Temperature"].copy(), errors = "coerce")
df_sk_co2_temp_wide_std.head()

#Mean and sd for emissions and temperature of SK in standard units
#Where x refers to emissions statistics
#Where y refers to temperature statistics

mean_x_su = np.mean(list(df_sk_co2_temp_wide_std["Emissions"]))
mean_y_su = np.mean(list(df_sk_co2_temp_wide_std["Temperature"]))
sd_x_su = np.std(list(df_sk_co2_temp_wide_std["Emissions"]))
sd_y_su = np.mean(list(df_sk_co2_temp_wide_std["Temperature"]))

print("Emissions mean (su): ",
      mean_x_su,
      "Temperature mean (su): ",
      mean_y_su,
      "Emissions standard deviation (su): ",
      sd_x_su,
      "Temperature standard deviation (su): ",
      sd_y_su)

#Mean and sd for emissions and temperature of SK in non-standardized units
#Where x refers to emissions statistics
#Where y refers to temperature statistics

mean_x = np.mean(list(df_sk_co2_temp_wide_std ["Emissions"]))
mean_y = np.mean(list(df_sk_co2_temp_wide_std ["Temperature"]))
sd_x = np.std(list(df_sk_co2_temp_wide_std ["Emissions"]))
sd_y = np.std(list(df_sk_co2_temp_wide_std ["Temperature"]))

print("Emissions mean: ",
      mean_x,
      "Temperature mean: ",
      mean_y,
      "Emissions standard deviation: ",
      sd_x,
      "Temperature standard deviation: ",
      sd_y)

#correlation coefficient for emissions and temperature of SK
#where x refers to emissions statistics
#where y refers to temperature statistics

x=list(df_sk_co2_temp_wide_std["Emissions"])
y=list(df_sk_co2_temp_wide_std["Temperature"])
coeff = stats.pearsonr(x,y)
print("Correlation coefficient: ", coeff.statistic)

#Scaled emissions and temperature plot

scaled_plot = (ggplot(data = df_sk_co2_temp_wide_std, mapping = aes(x="Emissions", y="Temperature"))+
                        geom_point()+
                        geom_smooth(method = "lm", se=False, color = "blue")+
                 scale_x_continuous()+
               labs(title= "US CO2 Emissions and Temperature (1980-2014)",
                    x="Scaled Emissions (Metric Tonnes)",
                    y= "Scaled Temperature (Fahrenheit)")+
               ggsize(600, 400)
                       )

scaled_plot

#Summary plot
gggrid(plots = [co2_plot, tile_plot, facet_co2_temp_plot, scaled_plot], ncol = 2, widths = [5,5])

